In [1]:
import os
import pandas as pd

In [4]:
config = {"user_genre_dist_file":"./cornac/data_c/user_genre_dist.csv"}

actual_genre_dist = pd.read_csv(
            os.path.join(config["user_genre_dist_file"]),
            sep="\t",
        )
actual_genre_dist

,userID,Action,Thriller,Romance,Western,Children's,Mystery,Fantasy,Film-Noir,Documentary,Comedy,Adventure,Sci-Fi,Horror,Crime,Musical,War,Animation,Drama
0,0,0.029031,0.038749,0.054221,0.000000,0.128900,0.000000,0.017419,0.000000,0.000000,0.128687,0.024023,0.017418,0.000000,0.015483,0.087993,0.019415,0.148294,0.290368
1,1,0.157693,0.088141,0.061218,0.009615,0.000000,0.004808,0.002404,0.002404,0.000000,0.089744,0.047917,0.046314,0.003205,0.033654,0.000000,0.034295,0.000000,0.418588
2,2,0.147967,0.050813,0.017886,0.069106,0.013008,0.008130,0.014228,0.000000,0.000000,0.346342,0.176423,0.034146,0.012195,0.000000,0.004878,0.009756,0.013008,0.082113
3,3,0.376471,0.044118,0.011765,0.029412,0.014706,0.000000,0.029412,0.000000,0.000000,0.000000,0.106863,0.116667,0.063726,0.000000,0.000000,0.043137,0.000000,0.163725
4,4,0.071803,0.080713,0.072851,0.006289,0.012054,0.012054,0.000000,0.005241,0.037736,0.190775,0.014151,0.018868,0.033543,0.042453,0.006813,0.015723,0.010482,0.368449
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6035,6035,0.070938,0.086496,0.062260,0.009961,0.022997,0.014182,0.007197,0.007735,0.009141,0.179744,0.032422,0.083882,0.049272,0.026958,0.013807,0.015916,0.015681,0.291411
6036,6036,0.045794,0.169743,0.047321,0.010802,0.009774,0.025718,0.006175,0.019548,0.003086,0.172829,0.010807,0.083893,0.016977,0.033948,0.009772,0.026237,0.000000,0.307577
6037,6037,0.031249,0.000000,0.125001,0.000000,0.031249,0.000000,0.000000,0.000000,0.000000,0.364577,0.000000,0.000000,0.062498,0.000000,0.000000,0.062500,0.062501,0.260424
6038,6038,0.018855,0.053029,0.099998,0.006734,0.041582,0.069864,0.017676,0.026941,0.000000,0.290737,0.031489,0.028114,0.003367,0.000000,0.153532,0.028958,0.033167,0.095958
6039,6039,0.052331,0.062353,0.055394,0.006269,0.003783,0.016861,0.004657,0.009945,0.025703,0.191522,0.024500,0.052110,0.049449,0.025007,0.013040,0.025994,0.001164,0.379918

In [19]:
x = actual_genre_dist[actual_genre_dist["Documentary"]>0.00]
movies = pd.read_csv("./cornac/data_c/indexed_movies.csv")

movies = movies.drop(columns=movies.columns[0])

In [11]:
users = pd.read_csv("./cornac/data_c/u_id_mapping.csv", sep="\t")
users = users.drop(columns=users.columns[0])
gender_map = {"M": 0, "F": 1}
users["Gender"] = users["Gender"].map(gender_map)

In [17]:

rating_data_pd = pd.read_csv(
    "./cornac/data_c/indexed_interactions.csv",
    sep="\t",
    header=None,
    names=["userID", "itemID", "Rating", "Timestamp"],
)
# print(rating_data["itemID"].nunique())
# rating_data = rating_data.drop(columns=rating_data.columns[-1])
rating_data = rating_data_pd.to_numpy()
rating_data

array([[        0,         0,         5, 978300760],
       [        0,         1,         3, 978302109],
       [        0,         2,         3, 978301968],
       ...,
       [     6039,       365,         5, 956704746],
       [     6039,       152,         4, 956715648],
       [     6039,        26,         4, 956715569]])

In [24]:
m = pd.merge(rating_data_pd, movies, on="itemID", how="inner")
m

,userID,itemID,Rating,Timestamp,movieID,genres
0,0,0,5,978300760,1193,Drama
1,0,1,3,978302109,661,Animation|Children's|Musical
2,0,2,3,978301968,914,Musical|Romance
3,0,3,4,978300275,3408,Drama
4,0,4,5,978824291,2355,Animation|Children's|Comedy
...,...,...,...,...,...,...
999606,6039,772,1,956716541,1091,Comedy
999607,6039,1106,5,956704887,1094,Drama|Romance|War
999608,6039,365,5,956704746,562,Comedy|Drama
999609,6039,152,4,956715648,1096,Drama
999610,6039,26,4,956715569,1097,Children's|Drama|Fantasy|Sci-Fi

In [25]:
x = m[m["genres"].__contains__("Documentary")]

KeyError: False

In [22]:
rating_data_pd = pd.read_csv(
    "./testing_set_seed123_ml100k.csv",
    sep=",",
    header=None,
    names=["userID", "iid", "Rating"],
)
rating_data_pd["label"]=1
# rating_data_pd
users = pd.read_csv("./cornac/data_c/ml-100k/u_id_mapping.csv", sep="\t")
users = users.drop(columns=users.columns[0])
gender_map = {"M": 0, "F": 1}
users["Gender"] = users["Gender"].map(gender_map)
users

     Gender  userID
0         0       0
1         1       1
2         0       2
3         0       3
4         0       4
..      ...     ...
938       1     938
939       0     939
940       1     940
941       1     941
942       0     942

[943 rows x 2 columns]

In [12]:
new_df = pd.merge(rating_data_pd, users, on= "userID", how="inner")
new_df

       userID   iid  Rating  label  Gender
0         101   450       4      1       0
1         101   115       4      1       0
2         101   241       4      1       0
3         101   426       4      1       0
4         101   203       3      1       0
...       ...   ...     ...    ...     ...
20237     724  1015       4      1       0
20238     724   280       4      1       0
20239     724    98       3      1       0
20240     724   130       4      1       0
20241     724   175       4      1       0

[20242 rows x 5 columns]

In [13]:
new_df.columns = ["uid","iid","rating","label", "u_gender"]

       userID   iid  Rating  label
0         101   450       4      1
1         101   115       4      1
2         101   241       4      1
3         101   426       4      1
4         101   203       3      1
...       ...   ...     ...    ...
20237     724  1015       4      1
20238     724   280       4      1
20239     724    98       3      1
20240     724   130       4      1
20241     724   175       4      1

[20242 rows x 4 columns]

In [19]:
# new_df[new_df["Gender"]==1]
new_df.to_csv("m1100k.test.tsv")

In [27]:
rating_data_pd = pd.read_csv(
    "./testing_set_seed123_ml1m.csv",
    sep=",",
    header=None,
    names=["userID", "iid", "Rating"],
)
rating_data_pd["label"]=1
# rating_data_pd

users = pd.read_csv("./cornac/data_c/u_id_mapping.csv", sep="\t")
users = users.drop(columns=users.columns[0])
gender_map = {"M": 0, "F": 1}
users["Gender"] = users["Gender"].map(gender_map)

new_df = pd.merge(rating_data_pd, users, on= "userID", how="inner")
new_df

        userID   iid  Rating  label  Gender
0         6039   351       3      1       0
1         6039  2481       5      1       0
2         6039   159       4      1       0
3         6039   461       3      1       0
4         6039   288       4      1       0
...        ...   ...     ...    ...     ...
202331    2946   306       4      1       1
202332    2946   243       3      1       1
202333    2946   334       2      1       1
202334    2946   439       2      1       1
202335    2946  2234       3      1       1

[202336 rows x 5 columns]

In [28]:
# new_df[new_df["Gender"]==1]
new_df.to_csv("ml1m.test.tsv")

In [29]:
rating_data_pd = pd.read_csv(
    "./training_set_seed123_ml1m.csv",
    sep=",",
    header=None,
    names=["userID", "iid", "Rating"],
)
rating_data_pd["label"]=1
# rating_data_pd

users = pd.read_csv("./cornac/data_c/u_id_mapping.csv", sep="\t")
users = users.drop(columns=users.columns[0])
gender_map = {"M": 0, "F": 1}
users["Gender"] = users["Gender"].map(gender_map)

new_df = pd.merge(rating_data_pd, users, on= "userID", how="inner")
new_df

        userID   iid  Rating  label  Gender
0         6039   669       4      1       0
1         6039   128       5      1       0
2         6039   323       4      1       0
3         6039    41       4      1       0
4         6039  1092       5      1       0
...        ...   ...     ...    ...     ...
694573    2946   527       4      1       1
694574    2946  1925       3      1       1
694575    2946  2135       4      1       1
694576    2946   475       5      1       1
694577    2946   502       4      1       1

[694578 rows x 5 columns]

In [30]:
# new_df[new_df["Gender"]==1]
new_df.to_csv("ml1m.train.tsv")

In [31]:
rating_data_pd = pd.read_csv(
    "./val_set_seed123_ml1m.csv",
    sep=",",
    header=None,
    names=["userID", "iid", "Rating"],
)
rating_data_pd["label"]=1
# rating_data_pd

users = pd.read_csv("./cornac/data_c/u_id_mapping.csv", sep="\t")
users = users.drop(columns=users.columns[0])
gender_map = {"M": 0, "F": 1}
users["Gender"] = users["Gender"].map(gender_map)

new_df = pd.merge(rating_data_pd, users, on= "userID", how="inner")
new_df

        userID   iid  Rating  label  Gender
0         6039   364       4      1       0
1         6039   209       4      1       0
2         6039   617       5      1       0
3         6039   164       3      1       0
4         6039   693       5      1       0
...        ...   ...     ...    ...     ...
102692    2946   454       2      1       1
102693    2946   105       3      1       1
102694    2946   343       3      1       1
102695    2946  2099       4      1       1
102696    2946    89       3      1       1

[102697 rows x 5 columns]

In [32]:
new_df.to_csv("ml1m.validation.tsv")

In [34]:
rating_data_pd = pd.read_csv(
    "./val_set_seed123_ml100k.csv",
    sep=",",
    header=None,
    names=["userID", "iid", "Rating"],
)
rating_data_pd["label"]=1
# rating_data_pd
users = pd.read_csv("./cornac/data_c/ml-100k/u_id_mapping.csv", sep="\t")
users = users.drop(columns=users.columns[0])
gender_map = {"M": 0, "F": 1}
users["Gender"] = users["Gender"].map(gender_map)
new_df = pd.merge(rating_data_pd, users, on= "userID", how="inner")
new_df

       userID  iid  Rating  label  Gender
0         101   25       3      1       0
1         101  310       3      1       0
2         101  161       4      1       0
3         101  710       5      1       0
4         101  365       2      1       0
...       ...  ...     ...    ...     ...
10366     678  575       3      1       0
10367     678  360       4      1       0
10368     724  875       4      1       0
10369     724  710       3      1       0
10370     724  645       4      1       0

[10371 rows x 5 columns]

In [36]:
new_df.to_csv("ml100k.validation.tsv")

In [37]:
rating_data_pd = pd.read_csv(
    "./training_set_seed123_ml100k.csv",
    sep=",",
    header=None,
    names=["userID", "iid", "Rating"],
)
rating_data_pd["label"]=1
# rating_data_pd
users = pd.read_csv("./cornac/data_c/ml-100k/u_id_mapping.csv", sep="\t")
users = users.drop(columns=users.columns[0])
gender_map = {"M": 0, "F": 1}
users["Gender"] = users["Gender"].map(gender_map)
new_df = pd.merge(rating_data_pd, users, on= "userID", how="inner")
new_df

       userID  iid  Rating  label  Gender
0         101  177       4      1       0
1         101  289       4      1       0
2         101  153       4      1       0
3         101  361       4      1       0
4         101  321       4      1       0
...       ...  ...     ...    ...     ...
68669     724  421       1      1       0
68670     724  575       2      1       0
68671     724  964       1      1       0
68672     724  551       5      1       0
68673     724   51       4      1       0

[68674 rows x 5 columns]

In [39]:
new_df.to_csv("ml100k.train.tsv")